---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 曹振远.
--- DateTime: 2025/1/18 13:19
---
if redis.call("get", KEYS[1]) == ARGV[1] then
    --刷新过期时间
    return redis.call("pexpire", KEYS[1], ARGV[2])
else
    --设置key value和过期时间
    return redis.call("set", KEYS[1], ARGV[1], "NX", "PX", ARGV[2])
end
