---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 曹振远.
--- DateTime: 2025/1/17 15:12
---
if redis.call('get', KEYS[1] == ARGV[1]) then
    --延长key的过期时间
    return redis.call('pexpire', KEYS[1], ARGV[2])
end
